services:
  postgres:
    image: postgres:15-alpine
    container_name: carrefour_postgres
    environment:
      POSTGRES_DB: carrefour
      POSTGRES_USER: carrefour
      POSTGRES_PASSWORD: carrefour
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carrefour"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
